using System.Buffers;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;

namespace QuickProxyNet;

/// <summary>The Shadowsocks AEAD ciphers this library speaks (SIP004/SIP007).</summary>
internal enum ShadowsocksMethod
{
    /// <summary><c>aes-128-gcm</c>: 16-byte key and salt.</summary>
    Aes128Gcm,

    /// <summary><c>aes-192-gcm</c>: 24-byte key and salt. Not in the spec table; sing-box and shadowsocks-libev speak it, Xray does not.</summary>
    Aes192Gcm,

    /// <summary><c>aes-256-gcm</c>: 32-byte key and salt.</summary>
    Aes256Gcm,

    /// <summary><c>chacha20-ietf-poly1305</c>: 32-byte key and salt.</summary>
    ChaCha20Poly1305
}

/// <summary>
/// The Shadowsocks cipher table and key schedule: method-name resolution with by-name
/// rejection of everything else, <c>EVP_BytesToKey</c> for the master key, HKDF-SHA1 for the
/// per-session subkey, and the platform gate for ChaCha20-Poly1305.
/// </summary>
/// <remarks>
/// <para>
/// Written from the spec (shadowsocks.org/doc/aead) and validated against vectors generated by
/// an independent implementation; behaviour cross-checked with shadowsocks-crypto (MIT) and
/// go-shadowsocks2 (Apache-2.0). Salt length equals key length for every AEAD method — the
/// reason <c>aes-192-gcm</c> has a 24-byte salt, which the spec table (which omits that cipher)
/// cannot tell you.
/// </para>
/// <para>
/// Rejection is by name and lists what is accepted. There is no fallback: an unknown cipher
/// must not become "some cipher", a <c>none</c> cipher must not become a proxy that sends the
/// target address in the clear.
/// </para>
/// </remarks>
internal static class ShadowsocksCipher
{
    /// <summary>Size of every AEAD tag, in bytes.</summary>
    public const int TagSize = 16;

    /// <summary>Size of the AEAD nonce, in bytes (a little-endian counter).</summary>
    public const int NonceSize = 12;

    /// <summary>The largest key — and therefore salt — any supported method uses.</summary>
    public const int MaxKeySize = 32;

    /// <summary>The names <see cref="Resolve"/> accepts, for error messages.</summary>
    public const string AcceptedNames =
        "'aes-128-gcm', 'aes-192-gcm', 'aes-256-gcm' and 'chacha20-ietf-poly1305'";

    /// <summary>
    /// The accepted names that need only AES-GCM, for the message a platform without
    /// ChaCha20-Poly1305 gets. Kept next to <see cref="AcceptedNames"/> so the two lists cannot drift.
    /// </summary>
    public const string AcceptedAesNames = "'aes-128-gcm', 'aes-192-gcm' and 'aes-256-gcm'";

    /// <summary>The longest string <see cref="RejectionMessage"/> echoes back as a cipher name.</summary>
    private const int MaxEchoedNameLength = 40;

    private const int Md5Size = 16;
    private const int Sha1Size = 20;
    private const int StackScratchBytes = 256;

    /// <summary>The HKDF <c>info</c> string SIP004 fixes: the ASCII bytes <c>ss-subkey</c>.</summary>
    private static ReadOnlySpan<byte> SubkeyInfo => "ss-subkey"u8;

    /// <summary>Length of <see cref="SubkeyInfo"/>, for the stack buffer that holds it.</summary>
    private const int SubkeyInfoLength = 9;

    /// <summary>Key size of <paramref name="method"/> in bytes.</summary>
    public static int KeySize(ShadowsocksMethod method) => method switch
    {
        ShadowsocksMethod.Aes128Gcm => 16,
        ShadowsocksMethod.Aes192Gcm => 24,
        _ => 32
    };

    /// <summary>Salt size of <paramref name="method"/> in bytes — always equal to the key size.</summary>
    public static int SaltSize(ShadowsocksMethod method) => KeySize(method);

    /// <summary>The canonical wire name of <paramref name="method"/>.</summary>
    public static string Name(ShadowsocksMethod method) => method switch
    {
        ShadowsocksMethod.Aes128Gcm => "aes-128-gcm",
        ShadowsocksMethod.Aes192Gcm => "aes-192-gcm",
        ShadowsocksMethod.Aes256Gcm => "aes-256-gcm",
        _ => "chacha20-ietf-poly1305"
    };

    /// <summary>
    /// Resolves a cipher name, or throws a <see cref="NotSupportedException"/> that names the
    /// cipher found, the reason it is refused, and the names that are accepted.
    /// </summary>
    public static ShadowsocksMethod Resolve(string? method)
    {
        if (TryResolve(method, out ShadowsocksMethod resolved))
            return resolved;

        throw new NotSupportedException(RejectionMessage(method));
    }

    /// <summary>Resolves a cipher name without throwing.</summary>
    public static bool TryResolve(string? method, out ShadowsocksMethod resolved)
    {
        // Exactly the four canonical wire names, case-insensitively: a capitalised name is not a
        // different cipher, and accepting it downgrades nothing. No aliases — the spec table's
        // AEAD_* labels never appear in a link, and Xray's bare 'chacha20-poly1305' is ambiguous
        // (RejectionMessage says why); both are refused by name below.
        if (Is(method, "aes-128-gcm"))
        {
            resolved = ShadowsocksMethod.Aes128Gcm;
            return true;
        }

        if (Is(method, "aes-192-gcm"))
        {
            resolved = ShadowsocksMethod.Aes192Gcm;
            return true;
        }

        if (Is(method, "aes-256-gcm"))
        {
            resolved = ShadowsocksMethod.Aes256Gcm;
            return true;
        }

        if (Is(method, "chacha20-ietf-poly1305"))
        {
            resolved = ShadowsocksMethod.ChaCha20Poly1305;
            return true;
        }

        resolved = default;
        return false;
    }

    /// <summary>
    /// The message for a refused cipher name: what was found, why it is refused, what is accepted.
    /// </summary>
    public static string RejectionMessage(string? method)
    {
        string found = method ?? string.Empty;
        string reason;

        if (found.Length == 0)
            reason = "no cipher name was given";
        else if (found.StartsWith("2022-blake3-", StringComparison.OrdinalIgnoreCase))
            reason = "it is an AEAD-2022 (SIP022) cipher, a different protocol under the same URI scheme " +
                     "that needs BLAKE3, which the .NET BCL does not provide";
        else if (Is(found, "chacha20-poly1305"))
            reason = "the bare name is ambiguous: Xray reads it as 'chacha20-ietf-poly1305', early " +
                     "shadowsocks-libev meant the pre-RFC 64-bit-nonce draft by it; write 'chacha20-ietf-poly1305'";
        else if (found.StartsWith("aead_", StringComparison.OrdinalIgnoreCase))
            reason = "it is a spec-table identifier, not a wire name; use the lower-case dashed name";
        else if (Is(found, "xchacha20-ietf-poly1305"))
            reason = "there is no XChaCha20-Poly1305 in the .NET BCL";
        else if (Is(found, "none") || Is(found, "plain") || Is(found, "dummy"))
            reason = "it sends the target address and the payload unencrypted";
        else if (IsLegacyStreamCipher(found))
            reason = "it is a legacy stream cipher, which the Shadowsocks project has deprecated as broken";
        else if (IsUnimplementedAead(found))
            reason = "it is an AEAD outside the SIP004 table with no implementation here";
        else if (!LooksLikeCipherName(found))
            // A swapped 'password:method' puts the password here; echo its length, not its text.
            return $"Shadowsocks cipher is not supported: a {found.Length}-character value that is not a cipher " +
                   $"name was found where the cipher name belongs. Accepted: {AcceptedNames}.";
        else
            reason = "it is not a Shadowsocks cipher name this library recognises";

        return $"Shadowsocks cipher '{found}' is not supported: {reason}. Accepted: {AcceptedNames}.";
    }

    // A cipher name is short ASCII — letters, digits, '-' and '_' — with at least one separator
    // (every name outside the fixed single-word set handled above has one: aes-…, camellia-…,
    // rc4-md5, 2022-blake3-…). Anything else is echoed by length only, because the usual way a
    // non-name lands here is a swapped 'password:method'. A password shaped exactly like a cipher
    // name would still be echoed; that is the trade-off for naming what was found.
    private static bool LooksLikeCipherName(string value)
    {
        if (value.Length > MaxEchoedNameLength)
            return false;

        bool separator = false;
        foreach (char c in value)
        {
            if (c is '-' or '_')
                separator = true;
            else if (!char.IsAsciiLetterOrDigit(c))
                return false;
        }

        return separator;
    }

    /// <summary>
    /// Verifies the platform can run <paramref name="method"/>, throwing a
    /// <see cref="NotSupportedException"/> that names the OS otherwise.
    /// </summary>
    /// <remarks>
    /// <see cref="ChaCha20Poly1305.IsSupported"/> is false on every shipped Windows 10: the
    /// runtime requires build 20142, which only Windows 11 and Windows Server 2022 reach. About
    /// half of real-world <c>ss://</c> nodes use this cipher, so this message is one users see.
    /// </remarks>
    public static void EnsurePlatformSupport(ShadowsocksMethod method)
    {
        if (method == ShadowsocksMethod.ChaCha20Poly1305)
        {
            if (!ChaCha20Poly1305.IsSupported)
            {
                string hint = OperatingSystem.IsWindows()
                    ? " On Windows it needs build 20142 or later (Windows 11 / Windows Server 2022); no Windows 10 release has it."
                    : string.Empty;
                throw new NotSupportedException(
                    "Shadowsocks cipher 'chacha20-ietf-poly1305' requires ChaCha20-Poly1305, which this platform " +
                    $"({RuntimeInformation.OSDescription}) does not provide.{hint} Accepted on this platform: " +
                    $"{AcceptedAesNames}.");
            }

            return;
        }

        if (!AesGcm.IsSupported)
            throw new NotSupportedException(
                $"Shadowsocks cipher '{Name(method)}' requires AES-GCM, which this platform " +
                $"({RuntimeInformation.OSDescription}) does not provide.");
    }

    /// <summary>
    /// Derives the master key from <paramref name="password"/>: UTF-8 bytes through
    /// <see cref="EvpBytesToKey"/>. <paramref name="key"/> must be the method's key size.
    /// </summary>
    public static void DeriveMasterKey(string password, Span<byte> key)
    {
        ArgumentNullException.ThrowIfNull(password);

        int maxBytes = Encoding.UTF8.GetMaxByteCount(password.Length);
        byte[]? rented = maxBytes > StackScratchBytes ? ArrayPool<byte>.Shared.Rent(maxBytes) : null;
        Span<byte> utf8 = rented ?? stackalloc byte[StackScratchBytes];
        int written = 0;
        try
        {
            written = Encoding.UTF8.GetBytes(password, utf8);
            EvpBytesToKey(utf8.Slice(0, written), key);
        }
        finally
        {
            CryptographicOperations.ZeroMemory(utf8.Slice(0, written));
            if (rented is not null)
                ArrayPool<byte>.Shared.Return(rented);
        }
    }

    /// <summary>
    /// OpenSSL's <c>EVP_BytesToKey</c> with MD5, no salt and an iteration count of 1:
    /// <c>D_1 = MD5(password)</c>, <c>D_i = MD5(D_{i-1} ‖ password)</c>,
    /// <c>key = (D_1 ‖ D_2 ‖ …)[0..keyLen]</c>.
    /// </summary>
    /// <remarks>
    /// MD5 is what the protocol defines; there is no alternative. This is exactly what
    /// <c>openssl enc -k &lt;pass&gt; -md md5 -nosalt -P</c> prints as its key.
    /// </remarks>
    public static void EvpBytesToKey(ReadOnlySpan<byte> password, Span<byte> key)
    {
        int blockLength = Md5Size + password.Length;
        byte[]? rented = blockLength > StackScratchBytes ? ArrayPool<byte>.Shared.Rent(blockLength) : null;
        Span<byte> block = rented ?? stackalloc byte[StackScratchBytes];
        block = block.Slice(0, blockLength);
        // The digest is hashed into its own scratch and then copied to the front of `block`:
        // HashData does not promise to tolerate a destination that overlaps its source.
        Span<byte> digest = stackalloc byte[Md5Size];
        try
        {
            int written = 0;
            bool first = true;
            while (written < key.Length)
            {
                if (first)
                {
                    MD5.HashData(password, digest);
                    first = false;
                }
                else
                {
                    // block holds D_{i-1} in its first 16 bytes; append the password and hash.
                    password.CopyTo(block.Slice(Md5Size));
                    MD5.HashData(block, digest);
                }

                digest.CopyTo(block);

                int take = Math.Min(Md5Size, key.Length - written);
                digest.Slice(0, take).CopyTo(key.Slice(written));
                written += take;
            }
        }
        finally
        {
            CryptographicOperations.ZeroMemory(digest);
            CryptographicOperations.ZeroMemory(block);
            if (rented is not null)
                ArrayPool<byte>.Shared.Return(rented);
        }
    }

    /// <summary>
    /// Derives one direction's session subkey:
    /// <c>HKDF-SHA1(ikm = masterKey, salt, info = "ss-subkey", L = keyLen)</c>.
    /// <paramref name="subkey"/> must be the method's key size.
    /// </summary>
    /// <remarks>
    /// RFC 5869 spelled out with <see cref="HMACSHA1.HashData(ReadOnlySpan{byte}, ReadOnlySpan{byte}, Span{byte})"/>
    /// one-shots rather than <see cref="HKDF.DeriveKey(HashAlgorithmName, ReadOnlySpan{byte}, Span{byte}, ReadOnlySpan{byte}, ReadOnlySpan{byte})"/>:
    /// the BCL's Expand step creates an <c>IncrementalHash</c> per call, 272 bytes twice per
    /// connection, and every Shadowsocks subkey is at most two SHA-1 blocks long, so the
    /// unrolled form is both allocation-free and shorter. Byte-identical to the BCL on the pinned
    /// vectors and on 10 000 random <c>(ikm, salt)</c> pairs.
    /// </remarks>
    public static void DeriveSubkey(ReadOnlySpan<byte> masterKey, ReadOnlySpan<byte> salt, Span<byte> subkey)
    {
        if (subkey.Length > 2 * Sha1Size)
            throw new ArgumentOutOfRangeException(nameof(subkey), subkey.Length,
                $"A Shadowsocks subkey is at most {MaxKeySize} bytes.");

        ReadOnlySpan<byte> info = SubkeyInfo;
        Span<byte> prk = stackalloc byte[Sha1Size];
        Span<byte> block = stackalloc byte[Sha1Size];
        Span<byte> message = stackalloc byte[Sha1Size + SubkeyInfoLength + 1];
        try
        {
            // Extract: PRK = HMAC(salt, IKM).
            HMACSHA1.HashData(salt, masterKey, prk);

            // Expand, T(1) = HMAC(PRK, info ‖ 0x01).
            info.CopyTo(message);
            message[info.Length] = 0x01;
            HMACSHA1.HashData(prk, message.Slice(0, info.Length + 1), block);
            int take = Math.Min(Sha1Size, subkey.Length);
            block.Slice(0, take).CopyTo(subkey);

            if (subkey.Length > Sha1Size)
            {
                // T(2) = HMAC(PRK, T(1) ‖ info ‖ 0x02) — a 24- or 32-byte key needs its head.
                block.CopyTo(message);
                info.CopyTo(message.Slice(Sha1Size));
                message[Sha1Size + info.Length] = 0x02;
                HMACSHA1.HashData(prk, message.Slice(0, Sha1Size + info.Length + 1), block);
                block.Slice(0, subkey.Length - Sha1Size).CopyTo(subkey.Slice(Sha1Size));
            }
        }
        finally
        {
            // All three hold key material: the PRK outright, the blocks as subkey bytes.
            CryptographicOperations.ZeroMemory(prk);
            CryptographicOperations.ZeroMemory(block);
            CryptographicOperations.ZeroMemory(message);
        }
    }

    /// <summary>
    /// Fills <paramref name="salt"/> with fresh random bytes, redrawing an all-zero result the way
    /// shadowsocks-crypto's <c>random_iv_or_salt</c> does.
    /// </summary>
    public static void FillSalt(Span<byte> salt)
    {
        do
        {
            RandomNumberGenerator.Fill(salt);
        } while (salt.IndexOfAnyExcept((byte)0) < 0);
    }

    private static bool Is(string? value, string name) =>
        string.Equals(value, name, StringComparison.OrdinalIgnoreCase);

    // The full stream-cipher name list of shadowsocks-crypto's kind.rs, matched by shape:
    // the fixed names, plus aes-*/camellia-* in a stream mode.
    private static bool IsLegacyStreamCipher(string name)
    {
        if (Is(name, "table") || Is(name, "rc4") || Is(name, "rc4-md5") || Is(name, "chacha20") ||
            Is(name, "chacha20-ietf") || Is(name, "salsa20") || Is(name, "bf-cfb"))
            return true;

        bool block = name.StartsWith("aes-", StringComparison.OrdinalIgnoreCase) ||
                     name.StartsWith("camellia-", StringComparison.OrdinalIgnoreCase);
        if (!block)
            return false;

        return name.EndsWith("-ctr", StringComparison.OrdinalIgnoreCase) ||
               name.EndsWith("-cfb", StringComparison.OrdinalIgnoreCase) ||
               name.EndsWith("-cfb1", StringComparison.OrdinalIgnoreCase) ||
               name.EndsWith("-cfb8", StringComparison.OrdinalIgnoreCase) ||
               name.EndsWith("-cfb128", StringComparison.OrdinalIgnoreCase) ||
               name.EndsWith("-ofb", StringComparison.OrdinalIgnoreCase);
    }

    // AEADs that exist somewhere (aes-*-ccm, *-gcm-siv, sm4-*) but are outside SIP004 and
    // not implemented here.
    private static bool IsUnimplementedAead(string name) =>
        name.EndsWith("-ccm", StringComparison.OrdinalIgnoreCase) ||
        name.EndsWith("-gcm-siv", StringComparison.OrdinalIgnoreCase) ||
        name.StartsWith("sm4-", StringComparison.OrdinalIgnoreCase);
}
