<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0;net10.0;net11.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <MinVerTagPrefix>v</MinVerTagPrefix>
        <MinVerMinimumMajorMinor>3.0</MinVerMinimumMajorMinor>
    </PropertyGroup>
    <PropertyGroup>
        <PackageId>QuickProxyNet</PackageId>
        <Authors>Titlehhhh</Authors>
        <Company>Titlehhhh</Company>
        <Description>QuickProxyNet is a high-performance, zero-dependency .NET library for connecting to servers via HTTP, HTTPS, SOCKS4, SOCKS4a and SOCKS5 proxies, and via the VPN-style protocols VLESS, VMess and Trojan over tcp, ws or httpupgrade. Provides direct Stream access for low-level network operations. VLESS REALITY is available in the QuickProxyNet.Reality package.</Description>
        <PackageTags>proxy;networking;http;socks;vless;vmess;trojan;high-performance</PackageTags>
        <Copyright>Copyright © Titlehhhh 2024</Copyright>
        <RepositoryUrl>https://github.com/Titlehhhh/QuickProxyNet</RepositoryUrl>
        <PackageProjectUrl>https://github.com/Titlehhhh/QuickProxyNet</PackageProjectUrl>
    </PropertyGroup>
    
    <PropertyGroup>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>
    
    <PropertyGroup>        
        <PackageIcon>icon.png</PackageIcon>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
    </PropertyGroup>
    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)\icon.png" Pack="true" PackagePath="" Visible="false"/>
        <None Include="$(MSBuildThisFileDirectory)\LICENSE.txt" Pack="true" PackagePath="" Visible="false"/>
        <None Include="$(MSBuildThisFileDirectory)\readme.md" Pack="true" PackagePath=""/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="MinVer" Version="6.0.0" PrivateAssets="All"/>
        <PackageReference Include="DotNet.ReproducibleBuilds" Version="1.2.4" PrivateAssets="All"/>
        <PackageReference Include="ConfigureAwait.Fody" Version="3.3.2" PrivateAssets="All"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="QuickProxyNet.Tests"/>
        <InternalsVisibleTo Include="QuickProxyNet.Benchmarks"/>
    </ItemGroup>

</Project>
