name: release
on:  
  workflow_dispatch:
    inputs: 
      NugetApiUrl:
        description: API URL

jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 9.x
      
      - run: chmod +x ./build.sh
      - name: Push to NuGet        
        run: ./build.sh Push --Confuguration Release --NugetApiUrl ${{github.event.inputs.NugetApiUrl}} --NugetApiKey ${{ secrets.NUGET_API_KEY }} --GithubApiKey ${{secrets.GITHUB_TOKEN}}